version: "3.8"

services:

  elastic:
    container_name: elastic
    extends:
      file: service-elastic.yml
      service: elastic
    volumes:
      - vl_elastic:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    depends_on:
      elastic:
        condition: service_healthy
    extends:
      file: service-kibana.yml
      service: kibana

  metricbeat:
    container_name: metricbeat
    depends_on:
      elastic:
        condition: service_healthy
      kibana:
        condition: service_healthy
    extends:
      file: service-metricbeat.yml
      service: metricbeat

  filebeat:
    container_name: filebeat
    depends_on:
      elastic:
        condition: service_healthy
    extends:
      file: service-filebeat.yml
      service: filebeat

  logstash:
    container_name: logstash
    depends_on:
      elastic:
        condition: service_healthy
      kibana:
        condition: service_healthy
    extends:
      file: service-logstash.yml
      service: logstash

volumes:
  vl_certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './config/certs'
  vl_elastic:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./data/elastic
  vl_filebeat:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/filebeat'
  vl_kibana:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/kibana'
  vl_logstash:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/logstash'
  vl_metricbeat:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/metricbeat'
  

networks:
  default:
    name: elastic
    external: false
